name: app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  
flutter:
  uses-material-design: true
